#!/bin/bash
#  php add_tree.php --list-trees
for y in {3,5,6,8,12,13,14,15,16}
 do
  for i in $( php -q cacti/cli/add_tree.php --list-nodes --tree-id=${y}|awk '{print $2}'|egrep '[0-9]{1,10}'  ); do
   /usr/bin/php -q cacti/cli/delete_tree.php --tree-id=$i
  done
done

php -q cacti/plugins/autom8/autom8_add_tree.php
